apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-service
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    app: techtrends
    tag: udacity
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: LoadBalancer