apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: techtrends
    tag: udacity
  name: techtrends-udacity-helm
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: techtrends
      tag: udacity
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: techtrends
        tag: udacity
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: IfNotPresent
        name: techtrends-udacity
        resources:
          requests:
            cpu: 50m
            memory: 256Mi
          limits:
            cpu: 50m
            memory: 256Mi
        ports:
        - containerPort: 3111
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3111
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3111
