apiVersion: v1
kind: Service
metadata:
  labels:
    app: techtrends
    tag: udacity
  name: techtrends-service
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
  - protocol: TCP
    port: 8111
    targetPort: 80
  selector:
    app: techtrends
    tag: udacity
  type: ClusterIP