apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: techtrends
    tag: udacity
  name: techtrends-udacity
  namespace: techtrends-udacity
spec:
  replicas: 3
  selector:
    matchLabels:
      app: techtrends
      tag: udacity
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: techtrends
        tag: udacity
    spec:
      containers:
      - image: hosamelbasiony/techtrends-udacity:version1.0
        imagePullPolicy: IfNotPresent
        name: techtrends-udacity
        resources:
          requests:
            cpu: 50m
            memory: 256Mi