apiVersion: v1
kind: Service
metadata:
  labels:
    app: techtrends
    tag: udacity
  name: techtrends-service
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
  - protocol: {{ .Values.service.protocol }}
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  selector:
    app: techtrends
    tag: udacity
  type: {{ .Values.service.type }}